app/Seek/seek/provider/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email



class BookingForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),
                            Email()])
    submit = SubmitField('Book Service')

app/Seek/seek/provider/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from seek import db
from seek.models import Provider
from seek.provider.forms import BookingForm

provider = Blueprint('provider', __name__)


@provider.route('/providers')
@login_required
def providers():
    return render_template('providers.html', title='Welcome to Seek-Service')

@provider.route('/services')
@login_required
def services():
    return render_template('services.html', title='Welcome to Seek-Service')

@provider.route('/order', methods=['GET', 'POST'])
@login_required
def order():
    form = BookingForm()
    if form.validate_on_submit():
        flash('Your booking has been recorded! You will receive an email shortly with the booking details.', 'success')
        return redirect(url_for('provider.services'))
    return render_template('order.html', title='Booking well completed', form=form)

app/Seek/seek/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from seek import bcrypt, db
from seek.models import User, Provider
from seek.users.forms import RegistrationForm, LoginForm, SignupForm

users = Blueprint('users', __name__)


@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('provider.services'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('provider.services'))
        else:
            flash('Invalid username or Password', 'danger')
    title = "house booking service login"
    return render_template('login.html',form = form, title=title)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("provider.services"))

app/Seek/seek/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@1,300&family=Lobster&family=Righteous&family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
    <div class="container-fluid" 
    style="background: #00c6ff;
    background: -webkit-linear-gradient(to bottom, #0072ff, #00c6ff);
    background: linear-gradient(to bottom, #0072ff, #00c6ff);
    height: 800px;
    ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <h1
                        style="color: white;
                        font-family: 'Righteous', cursive;
                        text-align: center;
                        margin-top: -2;
                        font-size: 70px;
                        ">
                        Welcome to Seek-Service
                    </h1> 
                </div>
            </div></br>
            <div class="row">
                <div class="col-md-6">
                    <div class="card" style="padding: 10px;">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4 text-center">Register as a Service Provider Today</legend>
                                <div class="form-group">
                                    {{ form.username.label(class="form-control-label") }}
                                    {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.username.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.phone_number.label(class="form-control-label") }}
                                    {% if form.phone_number.errors %}
                                        {{ form.phone_number(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.phone_number.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.phone_number(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label(class="form-control-label") }}
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.confirm_password.label(class="form-control-label") }}
                                    {% if form.confirm_password.errors %}
                                        {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.confirm_password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.confirm_password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-outline-info") }}
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card" style="padding: 10px;">
                        <form method="POST" action="">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4 text-center">Join First To Book a Service Provder</legend>
                                <div class="form-group">
                                    {{ form.username.label(class="form-control-label") }}
                                    {% if form.username.errors %}
                                        {{ form.username(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.username.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.username(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.email.label(class="form-control-label") }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.email(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password.label(class="form-control-label") }}
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.confirm_password.label(class="form-control-label") }}
                                    {% if form.confirm_password.errors %}
                                        {{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
                                            <div class="invalid-feedback">
                                                {% for error in form.confirm_password.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                    {% else %}
                                        {{ form.confirm_password(class="form-control form-control-lg") }}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="form-group">
                                {{ form.submit(class="btn btn-outline-info") }}
                            </div>
                        </form>
                    </div>
                    <div class="border-top pt-3">
                        <small class="text-muted" style=" color:white; font-weight: bold;">
                            Already Have An Account? <a  style="color: white;" class="ml-2" href="{{ url_for('users.login') }}">Log In</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/Seek/seek/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='service.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@1,300&family=Lobster&family=Righteous&family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Service Providers</title>
    {% endif %}    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dar sticky-top">
            <div class="navbar-nav mr-auto">
                <a class="navbar-brand" style="color: white;font-family: 'Righteous', cursive; font-size: 20px;" href="{{ url_for('main.home') }}">Seek-Service</a>
                <a class="nav-link " style="color: white;" href="{{ url_for('provider.services') }}">Book A Service</a>
            </div>
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-link nav-item" style="color: white;" href="{{ url_for('users.logout') }}">Log Out</a>
                {% else %}
                <a class="nav-link nav-iteml-auto" style="color: white;" href="{{ url_for('users.login') }}">Log In</a>
                <a class="nav-link nav-item" style="color: white;" href="{{ url_for('main.home') }}">Sign Up</a>
                {% endif %}
            </div>
        </nav>
    </header>
    </br>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div id="list-example" class="list-group">
                    <a class="list-group-item list-group-item-action" href="#list-item-1">Interior Decor</a>
                    <a class="list-group-item list-group-item-action" href="#list-item-2">Plumbing</a>
                    <a class="list-group-item list-group-item-action" href="#list-item-3">Gardening</a>
                    <a class="list-group-item list-group-item-action" href="#list-item-4">House cleaning</a>
                    <a class="list-group-item list-group-item-action" href="#list-item-4">etc</a>
                  </div>
            </div>
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %} {% endblock %}
            </div>
            <div class="col-md-2">
                <p 
                    style="background: #00c6ff;
                    background: -webkit-linear-gradient(to bottom, #0072ff, #00c6ff);
                    background: linear-gradient(to bottom, #0072ff, #00c6ff);
                    height: 300px; width: 250px; border-radius: 10px; margin-top: 75px;
                    font-family: 'Shadows Into Light', cursive; color: white; text-align: center; font-size: 25px;">
                        </br>Our goal is to deliver value based quality services in the professional home services providers
                        </br> while increasing market share across East Africa.
                </p>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/Seek/seek/templates/login.html
{% extends 'layout.html' %}
    {% block content %}
        <div class="card" style="padding: 10px; background-color: white;">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="check">
                        {{ form.remember(class='form-check-input') }}
                        {{ form.remember.label(class='form-check-label') }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
                <small class="muted ml-2">
                    <a href="#">Forgot password?</a>
                </small>
            </form>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an An Account? <a class="ml-2" href="{{ url_for('main.home') }}">Sign Up Now</a>
            </small>
        </div>
    {% endblock %}

app/Seek/seek/templates/order.html
{% extends 'layout.html' %}
{% block content %}
<div class="card" style="padding: 10px; background-color: white;">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Booking A Service</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

app/Seek/seek/templates/providers.html
{% extends 'layout.html' %}
{% block content %}
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/female.jpg') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">Jane</h5>
                    <h5>Interior Decor</h5>
                    <hr>
                    <p>This service is one of the best we offer.</p>
                    <p>We design your house according to your liking and style.</p>
                    <p>Our team never dissapoints when it commes to this exalarating job.</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
        </br>
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/male.png') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">John</h5>
                    <h5>Gardening</h5>
                    <hr>
                    <p>This service is effortlessly affordable.</p>
                    <p>We leave your garden in ship shape looking magnificent</p>
                    <p>The team is up to the task</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
        </br>
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/male.png') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">Philip</h5>
                    <h5>Plumbing</h5>
                    <hr>
                    <h2>Plumbering</h2>
                    <p>We offer this service at fair price.</p>
                    <p>We fix your pipes and sinks in jiffy.</p>
                    <p>Our team is harworking to deliver the best</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
        </br>
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/female.jpg') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">Joyce</h5>
                    <h5>Painting</h5>
                    <hr>
                    <p>Ever needed to paint your house in amazing colors?</p>
                    <p>Well we are the right people for this job.</p>
                    <p>We paint your house and make it like a wonder color imagination</p>
                    <p>Our team will definetly color your world</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/female.jpg') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">Kate</h5>
                    <h5>House Cleaning</h5>
                    <hr>
                    <p>Ever needed someone to clean your house since you have no energy to do it?</p>
                    <p>Well thats where we come to your aid by offering this services.</p>
                    <p>Our cleaners are professionals with experience.</p>
                    <p>You will surelly not regret their service to your house.</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
        <div class="card">
            <article class="media ml-2">
                <img class="rounded-circle mr-3 mt-2" style="width: 100px; height: 100px;" src="{{ url_for('static', filename='Images/female.jpg') }}">
                <div class="media-body">
                    <h5 class="mt-0" style = "text-decoration: none; font-weight: 700;">Agness</h5>
                    <h2>House Keeping</h2>
                    <hr>
                      <p>Ever wanted to go out for a trip and you had no one to look after your house while your gone?</p>
                      <p>Well our team keeps your house safety and makes sure everything is working great.</p>
                      <p>So no stressing how your house is ,just enjoy your trip while we look after it.</p>
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('provider.order') }}">Book Now</a>
                    </div>
                </div>
            </article>
        </div>
{% endblock %}

app/Seek/seek/templates/services.html
{% extends 'layout.html' %}
{% block content %}
    <h1 style="text-align:center; font-size: 45px; font-weight: bolder;">Services Available</h1>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">Interior design</h2></a>
    </div>
    </br>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">Gardening</h2></a>
    </div>
    </br>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">Plumbing</h2></a>
    </div>
    </br>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">Painting</h2></a>
    </div>
    </br>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">House Keeping</h2></a>
    </div>
    </br>
    <div style="background-color: blue; border-radius: 20px; height: 50px;">
        <a href="{{ url_for('provider.providers') }}" style="text-decoration: none;"><h2 style="text-align:center; color: white; padding: 10px;">House Cleaning</h2></a>
    </div>
{% endblock %}